### ISSUE TITLE
是否可以直接获取推荐视频

### ISSUE THREAD

**Issue by PastGone** [CuteReimu/bilibili#20]
我在api收集的文档里 看到有这个，但是这个库里没有，我想知道，这是为什么，谢谢。
我是否有其他简便的方法来达成我的目的。

**Comment by CuteReimu** [comment]
没加而已，之前按照优先级做的，比较重要的我先做了。需要的话我可以给你加上，或者你自己提pr也行，反正写法都一样。

**Comment by CuteReimu** [comment]
- GetTopRecommendVideo 获取首页视频推荐列表
- GetRecommendVideo 获取相关视频推荐列表
