### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rat857** [CuteReimu/bilibili#21]
目前只支持获取热评吗，我想按时间排序获取评论，目前是不是还不支持啊

**Comment by CuteReimu** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/list.md
是想要这个吗？
还是直接获取视频的热评？这个：
https://github.com/CuteReimu/bilibili/blob/3d048db7c4eb6baa19bb62d26fa6a3b6890b7011/video.go#L364

**Comment by rat857** [comment]
> https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/list.md 是想要这个吗？ 还是直接获取视频的热评？这个：
> 
> https://github.com/CuteReimu/bilibili/blob/3d048db7c4eb6baa19bb62d26fa6a3b6890b7011/video.go#L364

是这个https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/list.md，不要热评，想要按时间顺序获取到最新的评论

**Comment by CuteReimu** [comment]
加了
https://github.com/CuteReimu/bilibili/blob/483cc679a9c1c892fbc6aa7dbe67fa9ec79a4c40/comment.go#L47-L52
