### ISSUE TITLE
获取用户空间动态能否实现？

### ISSUE THREAD

**Issue by yangtfu** [CuteReimu/bilibili#28]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/dynamic/space.md

看了一下好像没有这个接口，可以免登录获取用户动态

**Comment by CuteReimu** [comment]
加了
https://github.com/CuteReimu/bilibili/blob/0b20685aa10f5f868a7a9ab018dbd843300ea916/dynamic.go#L1090-L1096
