### ISSUE TITLE
精简写法，整理架构（v2版本施工中。。。）

### ISSUE THREAD

**Issue by PastGone** [CuteReimu/bilibili#31]
为什么**许多方法**，要写成
```golang
func SetTimeout(timeout time.Duration) 
func (c *Client) SetTimeout(timeout time.Duration)
```
一个函数还要包一层。又没有多大的好处。
而事例中调用时用bilibili.SetTimeOut。
还要多写代码。似乎没有这个必要。

**Comment by CuteReimu** [comment]
为了应对这样的需求：我想要在程序里登录两个不同的号，这样用一个`Client`对象存登录信息就不行了。于是就可以这样写

```go
var err error
client1 := bilibili.New()
err = client.LoginWithQRCode(result1)
client2 := bilibili.New()
err = client.LoginWithQRCode(result2)
```

这个在[README.md](https://github.com/CuteReimu/bilibili?tab=readme-ov-file#%E5%90%8C%E6%97%B6%E7%99%BB%E5%BD%95%E5%A4%9A%E4%B8%AA%E8%B4%A6%E5%8F%B7)的最下面其实也写了用法。

当然了，对于你只需要登录一个号，直接调用`bilibili.XXXX`就行了，就不用那么麻烦。

很多库（例如go1.22版本的`log/slog`、例如`go-resty`、例如`logrus`等）也是采用了同样的写法。

**Comment by PastGone** [comment]
但是我只登一个号时，使用
```golang
client1 := bilibili.New()
err = client.LoginWithQRCode(result1)
```
比
``` golang
err=bilibili.LoginwithQRCode(result1)
```
在调用时并没有简单多少。最多，多一两行代码。
但是作为开发者来讲，反而要多写许多代码。
你举的例子，我用的不多。
但是针对于这对于这个代码库来讲,这实际上是没有必要的。
如果你同意的话，我想提交一个修改后的PR，去除这种`冗余`后的PR。

**Comment by PastGone** [comment]
此外我还在代码中看到这样的结构。
A——》std.A——》B——》std.B
我认为这也不是很利于维护。
另外，我觉得,可以可以听一下其他人的意见。
@yangtfu @Verthandii @rat857

**Comment by CuteReimu** [comment]
那如果这样的情况呢：我的代码有很多个包，都需要用到同一个`client`对象，那这个`client`应该放在哪呢？会给调用者带来一些麻烦。如果按照现在这样写，他就可以在所有的包都调用`bilibili.XXX()`了。

我们拿一个非常常用的配置库 https://github.com/spf13/viper 举例子，它就既支持`viper.XXX()`，又支持`v := viper.New()`。还有很多非常常用的库也都用的是这样的方式。

当然了，如果这个问题有合适的方解决决，我当然也不介意去掉这些冗余。考虑这个库也有几十个stars了，应该用的人蛮多的，如果真要改的话，我觉得可以直接切v2版本了。~（顺便更新到最新的Go版本）~

总结一下，我的意思就是：
- 如果能解决上面那个问题，我不介意去掉冗余。
- 如果真要弄的话，就切v2版本。~（顺便更新到最新的Go版本）~

**Comment by PastGone** [comment]
这其实不是什么大问题。可以看一下gin框架。

```go
ginServer := gin.Default()
Setting(&ginServer) //同一包里的调用
UserDB.Settings(&ginServer)//不同包的调用

ginServer.run()//
```

类似的

```go
client := bilibili.Default()
//Default()方法，可以把该配置的配置，比如logger，
//New()则把选择权，交给用户。这一点也可以借鉴gin

Setting(&client) //同一包里的调用
UserDB.Settings(&client)//不同包的调用

client.GetXXX()//
```

如果多个时

```go
client1 := bilibili.Default()
client2 := bilibili.Default()

//可以选择性的进行调用
Setting(&client1) 
UserDB.Settings(&client1)

client1.GetXXX()//
client2.GetXXX()//
```


如果各个包里都使用`bilibili.XXX()`的方式进行调用，

一是当从一个账号变为多个账号时，需要变更许多代码。

二是如果这个包调用了bilibili.SetTimeOut()，另一个包里就会变,

不太符合设计结构。

**Comment by RunsTp** [comment]
```golang
// 返回一个以初始化模式创建的 client
    // 这个client并非全局期client, 他的生命周期应当由调用者控制
    client := bilibili.Default()

    // client  使用with进行一些设置
    client.WithTimeout(time.Second).
        WithUser(user)
 
```
我认为user这个概念最好剥离出来，因为严格来讲client是可以复用的, 至于是把user作为属性放到client中，还是把client作为属性放到user中，这个可以做一点思考

同样我也比较支持从v2在做变化，我也可以来帮忙；但如果决定开v2，可以先考虑下一些设计上的思路

**Comment by CuteReimu** [comment]
行，可以开始弄。要不我直接把当前分支签到v1，主干切v2吧
