### ISSUE TITLE
这个New和Default要不要合成一个函数？

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#34]
https://github.com/CuteReimu/bilibili/blob/e1fb69ec7e088e8b3e3fe0bd08407fe7953a739d/client.go#L20-L27

**Comment by RunsTp** [comment]
我们可以使用一点options方案，New 允许传递 options 作为参数，这样给未来留有一定的可扩展性
如
```golang
func New(options ...func(*Server)) *Server {
  svr := &Server{}
  for _, o := range options {
    o(svr)
  }
  return svr
}
```
详细可以看 [这里](https://golang.cafe/blog/golang-functional-options-pattern.html)

而Default 则返回一个大部分场景使用的即可

**Comment by PastGone** [comment]
我赞成你所说的。
两个方法实际上都是可以存在的。
之前太仓促，没有把关系体现出来。
Default()可以直接调用New()，得到返回结果，然后再进行配置。
options的模式固然很好，但最好不要在New()使用，可以想个其他的方法。
New()返给用户一个纯净的对象就够了。

**Comment by PastGone** [comment]
个人感觉，引入option实在是大炮打蚊子。
---
而且这个问题，最先是说，要不要合并两个方法。
我的意见是不合并，尽管目前两个函数看起并没有什么差别。
我们可以更多推荐用户使用Default()，New()则是另一个选择。
---
至于option的引入，看情况吧。目前来看没有option，也不会有什么麻烦。

**Comment by CuteReimu** [comment]
我想了一下，我们底层肯定是用`go-resty`库做HTTP Client，而且实际上我们没有什么除了HTTP Client以外的参数需要设置，我们不妨就直接允许调用者直接传入一个`*resty.Client`，直接自行修改它的参数即可。

参考`resty`库的源码：

```go
// New method creates a new Resty client.
func New() *Client {
	cookieJar, _ := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
	return createClient(&http.Client{
		Jar: cookieJar,
	})
}

// NewWithClient method creates a new Resty client with given `http.Client`.
func NewWithClient(hc *http.Client) *Client {
	return createClient(hc)
}
```

那我们也用类似的方法定义吧：

```go
func New() *Client {
    // 返回一个我们默认参数的*bilibili.Client
}

func NewWithClient(rc *resty.Client) *Client {
    return &Client{restyClient: rc}
}

func (c *Client) GetRestyClient() *resty.Client {
    return c.rc
}
```

然后调用者可以这样用：

```go
c := bilibili.New()
c.GetRestyClient().SetTimeout(20 * time.Second) // 如果想自定义一些参数的话，就自行取出这个*resty.Client操作
```

最后，我们在README.md写上：登录之后不要随便修改`*resty.Client`的Cookies。

---

以下在顺便提一下我的另外一个构想：

<details>
<summary>点击展开</summary>

<br/>
有这样一个接口：

> *获取评论区明细_翻页加载*
>
> https://api.bilibili.com/x/v2/reply
>
> *请求方式：GET*
> 
> 认证方式：Cookie（SESSDATA）或APP
> 
> **url参数：**
> 
> | 参数名     | 类型 | 内容           | 必要性       | 备注                                                     |
> | ---------- | ---- | -------------- | ------------ | -------------------------------------------------------- |
> | access_key | str  | APP 登录 Token | APP 方式必要 |                                                          |
> | type       | num  | 评论区类型代码 | 必要         | [类型代码见表](readme.md#评论区类型代码)                 |
> | oid        | num  | 目标评论区 id  | 必要         |                                                          |
> | sort       | num  | 排序方式       | 非必要       | 默认为0<br />0：按时间<br />1：按点赞数<br />2：按回复数 |
> | nohot      | num  | 是否不显示热评 | 非必要       | 默认为0<br />1：不显示<br />0：显示                      |
> | ps         | num  | 每页项数       | 非必要       | 默认为20<br />定义域：1-20                                 |
> | pn         | num  | 页码           | 非必要       | 默认为1                                                  |

然后我们的代码是这样的：

https://github.com/CuteReimu/bilibili/blob/bb5cd963c0e3083d325e008ac28df4c3f6f739b3/comment.go#L211-L216

可以看出，有很多的参数实际上函数参数里面都没有填。而且因为B站经常会改接口加字段，我们这样定义函数这也不方便扩展，万一加字段后，调用者在`go get -u`之后还得修改自己的代码。我建议`v2`版本改成这样：

```go
import "github.com/spf13/cast"

func structToMap(s any) map[string]string {
    // 用反射的方式将结构体转成map
    // 其中uri后面的字符串就是key
    // 如果有omitempty，则零值就不填
    m := map[string]string
    // TODO m[key] = cast.ToString(value)
    return m
}

type GetVideoCommentParams struct {
    AccessKey string `uri:"access_key,omitempty"` // APP 登录 Token，不是APP方式可以填空
    Type int `uri:"type"` // 评论区类型代码
    Oid int `uri:"oid"` // 目标评论区 id
    Sort int `uri:"sort,omitempty"` // 排序方式
    Nohot int `uri:"nohot,omitempty"` // 是否不显示热评
    Ps int `uri:"ps,omitempty"` // 每页项数
    Pn int `uri:"pn,omitempty"` // 页码
}

func (c *Client) GetVideoComment(params GetVideoCommentParams) (*HotReply, error) {
    resp, err := c.rc.R().SetQueryParams(structToMap(params)).Get("https://api.bilibili.com/x/v2/reply")
    // TODO 后续处理
}
```

然后我们甚至可以写个Python脚本，自动根据Markdown表格生成结构体，以及注释，这个很简单。

另外Go1.22又支持泛型了，几乎我们的所有函数都可以写成这样：

```go
type paramHandler func(*Client, map[string]string)

func fillCsrf(c *Client, params map[string]string) {
	params["csrf"] = c.getCookie("bili_jct")
}

func execute[In, Out any](c *Client, method, url string, in In, handlers ...paramHandler) (Out, error) {
	params := structToMap(in)
	for _, handler := range handlers {
		handler(c, params)
	}
	resp, err := c.resty().R().SetQueryParams(params).Execute(method, url)
	var out Out
	if err != nil {
		return out, errors.WithStack(err)
	}
	data, err := getRespData(resp)
	if err != nil {
		return out, err
	}
	err = json.Unmarshal(data, &out)
	return out, errors.WithStack(err)
}

func (c *Client) GetVideoComment(params GetVideoCommentParams) (*HotReply, error) {
    const url = "https://api.bilibili.com/x/v2/reply"
    return execute[GetVideoCommentParams, *HotReply](c, resty.MethodGet, url, params)
    // 对于直播那种需要csrf参数的就 return execute[In, Out](c, resty.MethodGet, url, params, fillCsrf)
}
```

这样一来，我们开发的时候，对于大部分接口，结构体也可以自行生成，函数代码基本就两三行，开发起来就很简单了。

然后有两个问题：

- 函数的命名规范应该怎么样？
- 对于那些默认值不是0的，但是0有特殊含义的，并且还是可选的参数而言，我们应该怎么处理？

</details>

**Comment by PastGone** [comment]
你的三个问题，前两个都是大问题。
命名是真的让人头疼。
至于第二个问题，我个人觉得，可以有两个解决方法
1.写个工具类，自动生成代码，但会增加复杂度
2.手写，在函数内部添加判断，但会导致代码冗长
😢慢慢来吧，总会有好办法

**Comment by CuteReimu** [comment]
提了一个工具和命名规范

https://github.com/CuteReimu/bilibili/blob/v2/tools/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%8F%8A%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83.ipynb

另外专栏、评论、直播、登录改完了。

还差动态、收藏、私信、用户、视频、大会员。靠各位了

**Comment by PastGone** [comment]
补一个工具吧，可以把json格式的返回数据转为go结构体。配合着使用更好。
https://pastgone.github.io/json-to-go/

**Comment by CuteReimu** [comment]
> 补一个工具吧，可以把json格式的返回数据转为go结构体。配合着使用更好。
> https://pastgone.github.io/json-to-go/
> 

这个不用，你直接把json串粘贴到Goland里面，会自动转。。。

**Comment by PastGone** [comment]
尴尬了，这个我还真不知道。
