### ISSUE TITLE
withParams方法需要支持[]string和[]int

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#38]
https://github.com/CuteReimu/bilibili/blob/e00cea095f7962e72928143b07c58e41b3799b84/fav.go#L52-L59

**Comment by RunsTp** [comment]
好的，我稍晚点处理

**Comment by CuteReimu** [comment]
> 我认为还是需要以struct的形式传递，但是新增一个tag， join 使用此tag时使用 `,`转为string 如果需要自定义切分使用  join=# 代表使用`#`
是struct，我发的链接是改之前的，现在改不了。我希望你支持这个：
```go
type Param struct {
    Ids []int `request:"query`
}
```
会变成"ids=1,2,3"。
现在不知道支不支持，应该是不支持的
