### ISSUE TITLE
需要支持wbi

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#41]
目前，我们的很多搜索类接口（例如搜索视频）都会返回“-403:非法访问”的错误。原因如下：

> 自 2023 年 3 月起，Bilibili Web 端部分接口开始采用 WBI 签名鉴权，表现在 REST API 请求时在 Query param 中添加了 w_rid 和 wts 字段。WBI 签名鉴权独立于 [APP 鉴权](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/APP.md) 与其他 Cookie 鉴权，目前被认为是一种 Web 端风控手段。
> 
> 经持续观察，大部分查询性接口都已经或准备采用 WBI 签名鉴权，请求 WBI 签名鉴权接口时，若签名参数 w_rid 与时间戳 wts 缺失、错误，会返回 v_voucher（推测为内部记录错误请求的 ID 方便 Debug），如：
> 
> ```json
> {"code":0,"message":"0","ttl":1,"data":{"v_voucher":"voucher_******"}}
> ```

相关文档：https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md

为了使这些接口可用，我们需要支持wbi。

**Comment by RunsTp** [comment]
我稍晚实现下这个
