### ISSUE TITLE
SetRawCookies好像有bug

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#44]
https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/client.go#L51-L56

https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/client.go#L63-L70

这个`SetRawCookies`好像有bug。

### 测试代码

```go
func TestCookies(t *testing.T) {
	c := New()
	c.SetCookiesString("a=1\nb=2")
	t.Log(c.GetCookies())

	c1 := New()
	c1.SetRawCookies("a=1\nb=2")
	t.Log(c1.GetCookies())
}
```

### 输出结果

```console
=== RUN   TestCookies
    cookie_test.go:62: [a=1 b=2]
    cookie_test.go:66: []
--- PASS: TestCookies (0.00s)
PASS
```

**Comment by CuteReimu** [comment]
要不直接把这一段全删了吧

https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/client.go#L58-L75

参考README.md

https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/README.md#L135-L145

和

https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/README.md#L167-L174

调用者也应该很容易自己想到这样使用（如果他实在想要获得这个cookies切片的话，但我觉得一般没有这个需求）：

```go
cookies := client.Resty().Cookies
client.Resty().SetCookies(cookies)
```

而`SetRawCookies`跟`SetCookiesString`好像表达的意思就是一样的吧？

直接删了你觉得怎么样？

**Comment by CuteReimu** [comment]
还有一个问题，你提交上来的`wbi_test.go`有没有包含你的登录信息

**Comment by RunsTp** [comment]
> 还有一个问题，你提交上来的`wbi_test.go`有没有包含你的登录信息

这是一个 无痕的cookies 没事的。

**Comment by RunsTp** [comment]
> https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/client.go#L51-L56
> 
> https://github.com/CuteReimu/bilibili/blob/433bf25da0272e25ee239a57d0f74afb65c6d9f5/client.go#L63-L70
> 
> 这个`SetRawCookies`好像有bug。
> 
> ### 测试代码
> ```go
> func TestCookies(t *testing.T) {
> 	c := New()
> 	c.SetCookiesString("a=1\nb=2")
> 	t.Log(c.GetCookies())
> 
> 	c1 := New()
> 	c1.SetRawCookies("a=1\nb=2")
> 	t.Log(c1.GetCookies())
> }
> ```
> 
> ### 输出结果
> ```
> === RUN   TestCookies
>     cookie_test.go:62: [a=1 b=2]
>     cookie_test.go:66: []
> --- PASS: TestCookies (0.00s)
> PASS
> ```

`SetRawCookies` 支持的是浏览器标准的格式, 这给了使用者直接从浏览器中copy cookie使用的便利性
我建议还是保留

**Comment by CuteReimu** [comment]
那我整理一下文档，标明一下它的用法
