### ISSUE TITLE
使用短信验证码登录时，发送短信验证码接口大概率返回86103错误

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#47]
可以参考 SocialSisterYi/bilibili-API-collect#756

目前没有什么好的解决办法，暂时将其标注在`README.md`中了。

https://github.com/CuteReimu/bilibili/blob/374714fa13f556a72c1528132a4188fcdc70fbf3/README.md?plain=1#L105

**Comment by RunsTp** [comment]
原则上还是建议用扫码，手机验证码各种角度来讲，都不推荐。

**Comment by CuteReimu** [comment]
你说的有道理。我本来想留一个good first issue在这里，算了，还是不管短信登录的问题了吧。

**Comment by CuteReimu** [comment]
> 这个返回86103有解吗？好像没办法一样

最好不要使用短信登录。

如果非要使用，建议去 https://github.com/SocialSisterYi/bilibili-API-collect/issues 寻找解决方法。
