### ISSUE TITLE
是否有必要把go版本号改成1.18？

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/bilibili#51]
考虑到使用者不一定更新了go版本，而我们的v2版本貌似是从1.18之后都支持，并且go自身是旧版本兼容的。我们是否有必要改成我们支持的go最小版本？

**Comment by PastGone** [comment]
可以，但是你确定真的没问题吗？

**Comment by CuteReimu** [comment]
> 可以，但是你确定真的没问题吗？

其它人引用这个库的时候，如果他是1.22，他可以引用1.18。但如果他是1.18，则不能引用1.22。

**Comment by PastGone** [comment]
呃，前天，我写那个工具的时候，我就遇到了，我之前是1.21，现在是1.22了。如果没问题的话，你就降吧

**Comment by RunsTp** [comment]
先开一个降低版本的分支看下其他依赖的情况。
不过我不推荐降到1.18，我更推荐降到1.19，因为当初1.18是22年03月发布的，而1.19是22年05月发布的，本身就是因为1.18有一些泛型问题，而这两个版本间隔足够短，这代表大部分用户可能要么是1.17及以下或者1.19及以上。

**Comment by CuteReimu** [comment]
我看了一下，我们依赖的库只有 `github.com/spf13/cast` 是1.19，其它都是更早。

然后看了一下1.19到1.22的变化：

- 1.22 支持了 `for i := range 10` 的语法，我们没用到。
- 1.22 改为`for`循环每次循环的循环变量改成用一个新的了。我们没有用到`for`里面套`go`的情况，所以也没影响。
- 1.22 新增了`math/rand/v2`包，我们没用到，只用了`crypto/rand`包。
- 1.21 `min`、`max`、`clear`函数，`log/slog`包，这几个我们都没用到。
- 1.21 `slices`包、`maps`包、`cmp`包，我们虽然没用到，但是是非常有用的工具函数。不过我考虑了一下，我们写SDK貌似不太需要这些工具类。
- 1.20 更新了http相关的一些库，但是跟我们没什么关系，我们直接调用的`resty`库，它现在还是1.16
- 1.20 错误支持`unwrap`，跟我们的调用者有关，跟我们其实没啥关系。
- 1.20 `unsafe`包的一些改动，跟我们没什么关系。允许切片转数组，跟我们也没什么关系。

综上，我认为降到1.19问题不大，可能少了一些标准库里的函数，对未来开发会有影响，但是我认为我们是SDK开发，大概率是没有影响的。

而且我也测过了，其实降到1.18也不会有编译错误。有没有未发现的错误，其实可以等以后再有人反馈吧，至少可以保证大部分接口不会有问题（

**Comment by CuteReimu** [comment]
我在降版本的时候发现了一个问题：

https://github.com/CuteReimu/bilibili/blob/34d1af27be20db3899035424a5579906a2c49ed6/util_test.go#L157-L168

这个`maps.Equals`比较两个`map`时，显然是需要比较`k1 == k2 && v1 == v2`的，然而，必须`k1`和`k2`都是`comparable`才可以进行`==`比较。而这里是一个`map[string]any`，`any`并不显式为`comparable`，即使其实它的值确实都是`string`或`int`或`*int`，它也会出现编译错误。

这个编译错误在Go1.20得到了解决，这种情况不再会出现编译错误。

因此降到Go1.19会引发`util_test.go`的编译错误。但仅仅是test文件，并不影响整个库。

对此你们有什么建议？

引用：https://go.dev/doc/go1.20

> [Comparable types](https://go.dev/ref/spec#Comparison_operators) (such as ordinary interfaces) may now satisfy `comparable` constraints, even if the type arguments are not strictly comparable (comparison may panic at runtime). This makes it possible to instantiate a type parameter constrained by `comparable` (e.g., a type parameter for a user-defined generic map key) with a non-strictly comparable type argument such as an interface type, or a composite type containing an interface type.

**Comment by RunsTp** [comment]
> 我在降版本的时候遇到了一个问题：
> 
> https://github.com/CuteReimu/bilibili/blob/34d1af27be20db3899035424a5579906a2c49ed6/util_test.go#L157-L168
> 
> 这个`maps.Equals`比较两个`map`时，显然是需要比较`k1 == k2 && v1 == v2`的，然而，必须`k1`和`k2`都是`comparable`才可以进行`==`比较。而这里是一个`map[string]any`，`any`并不显式为`comparable`，即使其实它的值确实都是`string`或`int`或`*int`，它也会出现编译错误：*`any` does not implement `comparable`*。IDE提示：*无法将`any`用作类型`comparable`。从 Go 1.20 开始，基本接口满足`comparable`类型检查规则。*
> 
> 这个编译错误在Go1.20得到了解决，这种情况不再会出现编译错误。
> 
> 因此降到Go1.19会引发`util_test.go`的编译错误。但仅仅是test文件，并不影响整个库。
> 
> 对此你们有什么建议？
> 
> 引用：https://go.dev/doc/go1.20
> 
> > [Comparable types](https://go.dev/ref/spec#Comparison_operators) (such as ordinary interfaces) may now satisfy `comparable` constraints, even if the type arguments are not strictly comparable (comparison may panic at runtime). This makes it possible to instantiate a type parameter constrained by `comparable` (e.g., a type parameter for a user-defined generic map key) with a non-strictly comparable type argument such as an interface type, or a composite type containing an interface type.
> 
> 附上`maps`包的`Equals`函数：
> 
> ```go
> func Equals[M1, M2 ~map[K]V, K, V comparable](m1 M1, m2 M2) bool {
> 	if len(m1) != len(m2) {
> 		return false
> 	}
> 	for k, v1 := range m1 {
> 		if v2, ok := m2[k]; !ok || v1 != v2 {
> 			return false
> 		}
> 	}
> 	return true
> }
> ```

是不是类型推断挂了，你试试显式声明看看，如果也不行。也许可以写编译忽略，再不行就只能1.20了

**Comment by CuteReimu** [comment]
> 是不是类型推断挂了，你试试显式声明看看，如果也不行。也许可以写编译忽略，再不行就只能1.20了

`map[string]comparable` 这种肯定是不行的，`comparable`不能这样用，只能用在泛型里面：`[T comparable]`。

真的想解决的话，我目前能想到的只有一个思路，就是手动一个一个比较，反正是测试代码。

不然就只能1.20了。
