### ISSUE TITLE
多次调用SetCookiesString，原先client内的cookies不会被覆盖

### ISSUE THREAD

**Issue by yanyao2333** [CuteReimu/bilibili#68]
# 问题描述
多次调用SetCookiesString（或是登录），resty内原先的cookie不会被覆盖，而是直接把新的cookies附加在了后面

# 具体场景
执行以下操作：
```go
client.SetCookiesString(cookies) //从文件读取cookie后设置到client
client.LoginWithQRCode(...) //发现登录失效，需要重新扫码登录
```
此时，再调用`client.GetCookiesString()`发现输出了两组cookies，似乎是在获取到新的cookie后没有清空resty内原有cookie，虽然不影响使用，但如果多次执行这个操作（从文件读取cookie，重新登录，再次保存），就会导致cookie文件越来越长

请问这是预期行为吗？还是不应该这么使用？

**Comment by CuteReimu** [comment]
**首先，我认为这个应该不是预期行为。**

我看了一下`resty`库的`Client.SetCookies`方法的源码是这样的：

```go
func (c *Client) SetCookies(cs []*http.Cookie) *Client {
    c.Cookies = append(c.Cookies, cs...)
    return c
}
```

它是`append`到后面了，确实会越加越长。

我们的`SetCookiesString`和`SetRawCookies`方法都调用这个。我们的`execute`函数也有这样的调用：

https://github.com/CuteReimu/bilibili/blob/7f31348b0fcaed227f65294eb3c96146bc80f321/util.go#L63-L70

这确实是个麻烦。

@RunsTp 我们面临着这样几个问题：

1. 从逻辑上讲，当**HttpClient**收到返回`Set-Cookies`时，我们确实应该设置**Cookies**（如同上面这段代码的第70行），并且确实应该以`append`的形式设置。对于浏览器上的登出操作，会通过js代码清空对应的**Cookies**。**我们是否需要给调用者提供一个清除Cookies的方法？**
2. `resty`库的`Client.SetCookies`方法是纯粹的进行了`append`，**我们是否应该调整为如果遇到相同的key就覆盖？这样做有没有别的问题？**

**Comment by yanyao2333** [comment]
或许可以不用动SetCookiesString，只修改GetCookiesString，在导出cookies时对是否有重复key做检查？

因为是否有重复cookie对程序正常运行无影响。正常情况下开发者/用户是感知不到resty里存了重复cookie的，仅在调用GetCookiesString保存时才会发现，这么修改是改动成本最小的方式

**Comment by CuteReimu** [comment]
> 或许可以不用动SetCookiesString，只修改GetCookiesString，在导出cookies时对是否有重复key做检查？
> 
> 因为是否有重复cookie对程序正常运行无影响。正常情况下开发者/用户是感知不到resty里存了重复cookie的，仅在调用GetCookiesString保存时才会发现，这么修改是改动成本最小的方式

这样实际上改动成本是一样的，因为用户调用`GetCookiesString`，重启后再次调用`SetCookiesString`，其实内存里的**Cookies**变了。如果这样的话，和直接改`SetCookies`的效果是没有区别的。

**Comment by yanyao2333** [comment]
确实hhh
