### ISSUE TITLE
可以添加一下获取私信消息列表的接口吗？

### ISSUE THREAD

**Issue by Meayair** [CuteReimu/bilibili#8]
https://api.vc.bilibili.com/session_svr/v1/session_svr/get_sessions?session_type=1&group_fold=1&unfollow_fold=0&sort_rule=2&build=0&mobi_app=web

**Comment by CuteReimu** [comment]
是这个接口吗？`bilibili.GetSessionMessages(talkerId, sessionType, size, mobiApp)`

https://github.com/CuteReimu/bilibili/blob/6d108761bc7e7e958fe10c41cc0bb6f183831e45/message.go#L240

https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/message/private_msg.md#%E7%A7%81%E4%BF%A1%E6%B6%88%E6%81%AF%E8%AE%B0%E5%BD%95

你发的那个我在文档里没找到

**Comment by Meayair** [comment]
不是这个，文档里这个需要聊天的talkerId参数，是获取与某个人的聊天列表，我说的这个是获取私信消息列表的，文档里没看到，我在网页上抓的

**Comment by CuteReimu** [comment]
> https://api.vc.bilibili.com/session_svr/v1/session_svr/get_sessions?session_type=1&group_fold=1&unfollow_fold=0&sort_rule=2&build=0&mobi_app=web

给个返回的例子？

**Comment by CuteReimu** [comment]
试了一下，`group_fold`、`unfollow_fold`、`sort_rule`、`build`四个字段意义不明。
`session_type`的含义是，1：系统，2：用户，3：应援团。`mobi_app`是设备信息。

返回字段含义待补充。。。
